name: tmvkrpxl0Combat
version: 0.1
api-version: 1.16
main: tmvkrpxl0.src.tmvkrpxl0Combat
author: tmvkrpxl0
commands:
  tCombat:
    description: "tmvkrpxl0's random combat stuffs"
    aliases:
      - tcombat